(defpackage erlterm
  (:use :common-lisp)
  (:export decode-term
           encode-term))
(in-package :erlterm)

(defvar *fastest* '(optimize (speed 3) (safety 0) (debug 0)))
(defvar *interface* '(optimize (speed 3) (safety 2) (debug 1)))
(defvar *muffle-compiler-note* #+SBCL '(sb-ext:muffle-conditions sb-ext:compiler-note))

(deftype octet () '(unsigned-byte 8))
(deftype erl-atom () '(or keyword #+IGNORE atom-cache-ref))

(defvar *preserve-atom-case* t)
(defvar *minor-version* 1)

(defconstant +SMALL_INTEGER+ 97)
(defconstant +INTEGER+ 98)
(defconstant +SMALL_BIG+ 110)
(defconstant +LARGE_BIG+ 111)
(defconstant +FLOAT+ 99)
(defconstant +NEW_FLOAT+ 70)
(defconstant +ATOM+ 100)
(defconstant +SMALL_ATOM+ 115)
(defconstant +ATOM_CACHE_REF+ 82)
(defconstant +DIST_HEADER+ 68)
(defconstant +COMPRESSED+ 80)
(defconstant +STRING+ 107)
(defconstant +LIST+ 108)
(defconstant +NIL+ 106)
(defconstant +SMALL_TUPLE+ 104)
(defconstant +LARGE_TUPLE+ 105)
(defconstant +BINARY+ 109)
(defconstant +BIT_BINARY+ 77)
(defconstant +REFERENCE+ 101)
(defconstant +PORT+ 102)
(defconstant +PID+ 103)
(defconstant +NEW_REFERENCE+ 114)
(defconstant +FUN+ 117)
(defconstant +NEW_FUN+ 112)
(defconstant +EXPORT+ 113)
